apiVersion: apps/v1 
kind: Deployment
metadata:
  name: chathura-user-dev
  labels:
    app: chathura-user-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chathura-user-dev
  template:
    metadata:
      labels:
        app: chathura-user-dev
    spec:
     containers:
     - name: chathura-user-dev
       image: DIT
---
apiVersion: v1
kind: Service
metadata:
  name: chathura-user-dev 
  labels:
    app: chathura-user-dev
spec:
 #type: NodePort
 ports:
 - port: 8232
   targetPort: 8232
 selector:
  app: chathura-user-dev